name: DataLayer Basic Checks

on:
  push:
    branches: ["main"]
    paths:
      - "workdir/**"
      - ".github/**"

  pull_request:
    branches: ["**"]
    paths:
      - "workdir/**"
      - ".github/**"


jobs:
  build-and-check:
    strategy:
      fail-fast: true
      matrix:
        include:
          - RUNNER: ubuntu-latest
            PARAM: true
            PARAM_NAME: noop
          - RUNNER: ubuntu-latest
            PARAM: false
            PARAM_NAME: something
    uses: ./.github/workflows/common.yml
    with:
      PARAM: ${{ matrix.PARAM }}
      PARAM_NAME: ${{ matrix.PARAM_NAME }}
      RUNNER: ${{ matrix.RUNNER }}
    




# jobs:
#   publish-dev:
#     strategy:
#       fail-fast: true
#       matrix:
#         xyz: [1, 2, 3]
#     uses: ./.github/workflows/lib_publish_sdk-dev.yml
#     with:
#       module: data
#     secrets: inherit