name: DataLayer Basic Checks

on:
  push:
    branches: ["main"]
    paths:
      - "workdir/**"
      - ".github/**"

  pull_request:
    branches: ["**"]
    paths:
      - "workdir/**"
      - ".github/**"


jobs:
  build-and-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - RUNNER: ubuntu-latest
            PARAM: true
            PARAM_NAME: noop
          - RUNNER: ubuntu-latest
            PARAM: false
            PARAM_NAME: something
    uses: .github/workflows/common.yml
    with:
      PARAM: ${{ matrix.PARAM }}
      PARAM_NAME: ${{ matrix.PARAM_NAME }}
      RUNNER: ${{ matrix.RUNNER }}